onboarding = false

[ui]
agent_panel_sort = "spaces"

show_agent_labels_on_pane_borders = true

[ui.sound]
enabled = true

[ui.toast]
delivery = "terminal"

[theme]
name = "catppuccin"
auto_switch = false

[keys]
prefix = "ctrl+o"
split_vertical = "prefix+s"
split_horizontal = "prefix+d"
