model = "gpt-5-codex"
model_reasoning_effort = "high"

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.context7]
command = "npx"
args = [
  "-y",
  "@upstash/context7-mcp",
  "--api-key",
  "ctx7sk-372b01b4-fc80-42d3-8798-9a2be0a35073",
]

[mcp_servers.nuxt]
command = "npx"
args = ["mcp-remote", "https://mcp.nuxt.com/sse"]
